### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by blissi** [neilcrookes/dhl-ras#1]
Hallo,
first, thanks for your great work! This is really helpful.
I've got a question about maintenance: how did you create the JSON? Is this automated in some way or did you do it manually? If there is a newer version, how could the list be easily updated?

Thanks,
Steven

**Comment by neilcrookes** [comment]
Yes it's maintainable, and I do plan to maintain it. If there is a newer version, I could update this data relatively easily.
