### ISSUE TITLE
Outdated data

### ISSUE THREAD

**Issue by ajolinklog** [neilcrookes/dhl-ras#2]
The dataset looks promising for an application i am working on - sadly its outdated.

Would it be possible for you to update it for the newest version from march 2019?

Or alternately publish the script / code used to parse the pdf?

**Comment by neilcrookes** [comment]
I'll try and get it updated shortly.

**Comment by ajolinklog** [comment]
That would be awesome - thanks a lot!

**Comment by bzoks** [comment]
@neilcrookes, I guess you have some script for extracting this data from PDF... can you share it?

**Comment by hellcoderGIT** [comment]
2020 Data would be great. Quite incredible that DHL doesn't offer this list in any usable format...

**Comment by bashgeek** [comment]
@neilcrookes Would appreciate an update of the data, thanks a lot! :-)

**Comment by BenTen** [comment]
DHL updated the list the 12th April 2020
https://www.dhl.com/content/dam/downloads/g0/express/services/surcharges/dhl_express_remote_areas_id_id.pdf

**Comment by neilcrookes** [comment]
Many thanks to @zenekp for updating data to April 2020

**Comment by Endereco** [comment]
i guess we have a new dataset https://www.dhl.de/content/dam/images/Express/downloads/dhl-express-remote-areas-service.pdf - from Jan 2021
